---
argument_specs:
  main:
    short_description: "Deploy Teleport in a Split Architecture with PostgreSQL and FreeIPA using Podman Quadlets"
    options:
      teleport_deploy_cluster_name:
        type: "str"
        default: "teleport.internal.lab"
        description: "Teleport cluster domain name"
      teleport_deploy_postgres_host:
        type: "str"
        default: "postgres.internal.lab"
        description: "PostgreSQL database host FQDN"
      teleport_deploy_postgres_port:
        type: "int"
        default: 5432
        description: "PostgreSQL listener port"
      teleport_deploy_postgres_user:
        type: "str"
        default: "teleport_user"
        description: "PostgreSQL username for Teleport"
      teleport_deploy_postgres_password:
        type: "str"
        required: true
        description: "PostgreSQL password for Teleport"
      teleport_deploy_freeipa_host:
        type: "str"
        default: "idm.internal.lab"
        description: "FreeIPA / Red Hat IdM LDAPS server FQDN"
      teleport_deploy_freeipa_bind_dn:
        type: "str"
        default: "uid=teleport-bind,cn=sysaccounts,cn=etc,dc=internal,dc=lab"
        description: "FreeIPA bind DN for Teleport directory queries"
...
