---
- name: "Proxy | Ensure configuration and cert directories exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "/etc/teleport"
    - "/etc/teleport/certs"
    - "/etc/containers/systemd"

- name: "Proxy | Template Teleport Proxy Service configuration"
  ansible.builtin.template:
    src: "teleport-proxy.yaml.j2"
    dest: "/etc/teleport/teleport-proxy.yaml"
    mode: "0600"
    backup: true

- name: "Proxy | Template Teleport Proxy Quadlet unit file"
  ansible.builtin.template:
    src: "teleport-proxy.container.j2"
    dest: "/etc/containers/systemd/teleport-proxy.container"
    mode: "0644"
    backup: true

- name: "Proxy | Ensure Teleport Proxy systemd service is started and enabled"
  ansible.builtin.systemd_service:
    name: "teleport-proxy.service"
    state: started
    enabled: true
    daemon_reload: true
...
